'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import {
  Users,
  Radar,
  PenTool,
  BarChart3,
  Rocket,
  ArrowRight,
  ArrowUpRight,
  Check,
  Sparkles,
  Video,
  MessageSquare,
  Mail,
  Mic,
  Send,
  Star,
  ChevronDown,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { siteConfig } from '@/data/site-config'
import { cn } from '@/lib/utils'
import { RevealOnScroll } from '@/components/ui/reveal-on-scroll'
import { BlurFade } from '@/components/ui/blur-fade'

const iconMap: Record<string, React.ElementType> = {
  Users,
  Radar,
  PenTool,
  BarChart3,
  Rocket,
}

const fadeUp = {
  hidden: { opacity: 0, y: 24, filter: 'blur(4px)' },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    filter: 'blur(0px)',
    transition: {
      duration: 0.6,
      delay: i * 0.08,
      ease: [0.22, 1, 0.36, 1] as const,
    },
  }),
}

/* ─────────────────────────────────────────────────────────────
   Tool palette — small text chips with brand-tinted dots.
   ───────────────────────────────────────────────────────────── */
const toolColor: Record<string, string> = {
  Claude: '#D97757',
  GPT: '#10A37F',
  Perplexity: '#21808D',
  Exa: '#7C5CFF',
  Firecrawl: '#FF6A00',
  HeyGen: '#7B61FF',
  Synthesia: '#FF4D4D',
  ElevenLabs: '#1F2937',
  Descript: '#1FA37C',
  OpusClip: '#FF5C5C',
  Reddit: '#FF4500',
  GummySearch: '#9B5BFF',
  Notion: '#111111',
  Buffer: '#168EEA',
  TweetHunter: '#1DA1F2',
  Beehiiv: '#FFC940',
  Whisper: '#74AA9C',
  Otter: '#1F87FE',
  Riverside: '#7B61FF',
  Clay: '#5BC4F1',
  n8n: '#EA4B71',
  Make: '#6D31ED',
  Apollo: '#0066FF',
  Findymail: '#22C55E',
  BuiltWith: '#1F8FFF',
  Smartlead: '#FF6B35',
  Instantly: '#3B82F6',
  CustomerIO: '#7E5BEF',
  Klaviyo: '#000000',
  HubSpot: '#FF7A59',
  LinkedIn: '#0A66C2',
  X: '#0F0F0F',
  YouTube: '#FF0000',
  Instagram: '#E1306C',
  TikTok: '#0F0F0F',
  Manual: '#6B6B80',
  Webhook: '#9B9BAD',
}

type Tool = keyof typeof toolColor

type Stage = {
  label: string
  tools: Tool[]
}

type Tier = {
  label: string
  tone: 'mint' | 'sky' | 'lilac' | 'amber' | 'coral' | 'ink'
}

type Workflow = {
  slug: string
  title: string
  blurb: string
  icon: LucideIcon
  pillTag: string
  pillTone: string
  inputs: string[]
  stages: Stage[]
  tiers: Tier[]
  outputs: string[]
  featured?: boolean
}

const tierTone: Record<Tier['tone'], string> = {
  mint: 'bg-[#2D9D78]/12 text-[#1F7256] ring-[#2D9D78]/25',
  sky: 'bg-[#5B8DEF]/14 text-[#2C5BC4] ring-[#5B8DEF]/25',
  lilac: 'bg-[#7C5CFF]/12 text-[#4F39B5] ring-[#7C5CFF]/25',
  amber: 'bg-[#F0A500]/16 text-[#A87000] ring-[#F0A500]/25',
  coral: 'bg-coral/14 text-coral ring-coral/30',
  ink: 'bg-ink/[0.08] text-ink ring-ink/20',
}

const workflows: Workflow[] = [
  {
    slug: 'content-engines',
    title: 'ai content engines',
    blurb:
      'one topic in, twelve platform-ready pieces out. you review for 30 min, the engine ships the rest.',
    icon: PenTool,
    pillTag: 'Content',
    pillTone: 'bg-[#2D9D78]/12 text-[#2D9D78] ring-[#2D9D78]/25',
    inputs: ['Brand voice', 'Topic queue', 'Source library'],
    stages: [
      { label: 'Research & evidence', tools: ['Perplexity', 'Exa', 'Firecrawl'] },
      { label: 'Outline & angle', tools: ['Claude', 'GPT'] },
      { label: 'Draft + self-edit', tools: ['Claude', 'Notion'] },
      { label: 'Adapt per platform', tools: ['Claude', 'Buffer'] },
    ],
    tiers: [
      { label: 'Long-form', tone: 'mint' },
      { label: 'Threads', tone: 'sky' },
      { label: 'Shorts', tone: 'lilac' },
    ],
    outputs: ['Blog essay', 'X thread', 'LinkedIn post'],
  },
  {
    slug: 'ugc-video',
    title: 'ai ugc + short-form video',
    blurb:
      'a month of native reels in a weekend. avatars, voiceovers, and edits all autogenerated.',
    icon: Video,
    pillTag: 'Video',
    pillTone: 'bg-coral/10 text-coral ring-coral/25',
    inputs: ['Topic', 'Script outline', 'Brand assets'],
    stages: [
      { label: 'Script + hook', tools: ['Claude', 'GPT'] },
      { label: 'Avatar render', tools: ['HeyGen', 'Synthesia'] },
      { label: 'Voice clone', tools: ['ElevenLabs'] },
      { label: 'Auto-edit & captions', tools: ['Descript', 'OpusClip'] },
    ],
    tiers: [
      { label: 'Reel', tone: 'mint' },
      { label: 'Short', tone: 'sky' },
      { label: 'TikTok', tone: 'lilac' },
    ],
    outputs: ['Instagram', 'YouTube Shorts', 'X / TikTok'],
  },
  {
    slug: 'reddit-traffic',
    title: 'reddit-led traffic',
    blurb:
      'reddit is in 68% of ai answers. i build the playbooks that get you cited there, not just ranked.',
    icon: MessageSquare,
    pillTag: 'AI SEO',
    pillTone: 'bg-[#5B8DEF]/10 text-[#5B8DEF] ring-[#5B8DEF]/20',
    inputs: ['ICP keywords', 'Subreddit map', 'Brand POV'],
    stages: [
      { label: 'Trend mining', tools: ['Reddit', 'GummySearch'] },
      { label: 'Question matching', tools: ['Perplexity', 'Claude'] },
      { label: 'Native answer drafts', tools: ['Claude'] },
      { label: 'Cite-worthy publishing', tools: ['Manual', 'n8n'] },
    ],
    tiers: [
      { label: 'Educational', tone: 'mint' },
      { label: 'Comparison', tone: 'sky' },
      { label: 'Story', tone: 'lilac' },
    ],
    outputs: ['Google AIO cite', 'ChatGPT cite', 'Perplexity cite'],
  },
  {
    slug: 'email-lifecycle',
    title: 'email lifecycle, agentic',
    blurb:
      'the flows your funnel keeps forgetting — welcome, nurture, win-back, expansion. all on autopilot.',
    icon: Mail,
    pillTag: 'Lifecycle',
    pillTone: 'bg-[#F0A500]/15 text-[#A87000] ring-[#F0A500]/25',
    inputs: ['Customer events', 'Triggers', 'Brand voice'],
    stages: [
      { label: 'Behaviour listen', tools: ['n8n', 'CustomerIO'] },
      { label: 'Segment & route', tools: ['Clay', 'Make'] },
      { label: 'Personalize copy', tools: ['Claude', 'GPT'] },
      { label: 'Send + A/B test', tools: ['CustomerIO', 'Klaviyo'] },
    ],
    tiers: [
      { label: 'Welcome', tone: 'mint' },
      { label: 'Nurture', tone: 'sky' },
      { label: 'Win-back', tone: 'amber' },
    ],
    outputs: ['Onboarding flow', 'Re-engagement', 'Expansion'],
  },
  {
    slug: 'personal-brand',
    title: 'personal brand, on autopilot',
    blurb:
      'one 30-min recording → a week of linkedin, x, and newsletter. ai ghostwriter trained on your voice.',
    icon: Mic,
    pillTag: 'Most Aligned',
    pillTone: 'bg-coral text-white ring-coral/40',
    inputs: ['30-min recording', 'POV bank', 'Voice samples'],
    stages: [
      { label: 'Transcribe', tools: ['Whisper', 'Otter'] },
      { label: 'Structure & angle', tools: ['Claude'] },
      { label: 'Ghostwrite (your voice)', tools: ['Claude', 'GPT'] },
      { label: 'Schedule + ship', tools: ['Buffer', 'TweetHunter', 'Beehiiv'] },
    ],
    tiers: [
      { label: 'LinkedIn', tone: 'sky' },
      { label: 'X', tone: 'ink' },
      { label: 'Newsletter', tone: 'amber' },
    ],
    outputs: ['5 posts/wk', '3 threads/wk', '1 essay/wk'],
    featured: true,
  },
  {
    slug: 'outbound-gtm',
    title: 'ai outbound + gtm engineering',
    blurb:
      'signal-based prospecting, ai-personalized sequences, autonomous follow-ups. clay + n8n + claude.',
    icon: Send,
    pillTag: 'Outbound',
    pillTone: 'bg-ink/[0.08] text-ink ring-ink/15',
    inputs: ['ICP', 'Trigger signals', 'Domain list'],
    stages: [
      { label: 'Signal detection', tools: ['Clay', 'BuiltWith'] },
      { label: 'Enrich & verify', tools: ['Clay', 'Apollo', 'Findymail'] },
      { label: 'AI personalize', tools: ['Claude', 'GPT'] },
      { label: 'Send + follow-up', tools: ['Smartlead', 'Instantly', 'n8n'] },
    ],
    tiers: [
      { label: 'Tier 1', tone: 'mint' },
      { label: 'Tier 2', tone: 'sky' },
      { label: 'Tier 3', tone: 'lilac' },
    ],
    outputs: ['Calendar holds', 'Pipeline', 'Replies'],
  },
]

/* ─── Workflow components ──────────────────────────────────── */
function ToolChip({ name }: { name: Tool }) {
  const color = toolColor[name] ?? '#6B6B80'
  return (
    <span className="inline-flex items-center gap-1.5 px-2 py-[3px] rounded-md bg-white/85 ring-1 ring-ink/10 text-[10.5px] font-medium text-ink/85 tabular shadow-[0_1px_2px_rgba(26,26,46,0.04)]">
      <span
        className="h-1.5 w-1.5 rounded-full shrink-0"
        style={{ backgroundColor: color }}
        aria-hidden
      />
      {name}
    </span>
  )
}

function InputChip({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center px-2.5 py-1 rounded-full bg-white/70 ring-1 ring-ink/10 text-[10.5px] font-medium text-ink-muted tabular">
      {children}
    </span>
  )
}

function Connector() {
  return (
    <div className="flex justify-center" aria-hidden>
      <span className="block w-px h-3 bg-ink/15" />
    </div>
  )
}

function StageBox({ stage }: { stage: Stage }) {
  return (
    <div className="rounded-xl bg-white/75 ring-1 ring-ink/10 px-3 py-2.5 backdrop-blur-sm hover:ring-coral/30 hover:bg-white/90 transition-all">
      <p className="text-[12px] font-semibold text-ink leading-tight">
        {stage.label}
      </p>
      <div className="mt-1.5 flex flex-wrap gap-1">
        {stage.tools.map((tool) => (
          <ToolChip key={tool} name={tool} />
        ))}
      </div>
    </div>
  )
}

function TierPill({ tier }: { tier: Tier }) {
  return (
    <span
      className={cn(
        'flex-1 text-center text-[10.5px] font-bold uppercase tracking-[0.1em] px-2 py-1.5 rounded-full ring-1 tabular',
        tierTone[tier.tone],
      )}
    >
      {tier.label}
    </span>
  )
}

function OutputPill({ children }: { children: React.ReactNode }) {
  return (
    <span className="flex-1 text-center text-[11px] font-bold uppercase tracking-[0.08em] px-2 py-2 rounded-lg bg-ink text-white shadow-[0_6px_18px_-8px_rgba(26,26,46,0.6)] tabular">
      {children}
    </span>
  )
}

function WorkflowDiagram({ wf, index }: { wf: Workflow; index: number }) {
  const Icon = wf.icon

  return (
    <BlurFade delay={0.05 + index * 0.06} yOffset={20} blur={8}>
      <article
        id={wf.slug}
        className={cn(
          'relative h-full rounded-[24px] p-5 sm:p-6 backdrop-blur-md ring-1 transition-all scroll-mt-28',
          'shadow-[0_18px_50px_-20px_rgba(26,26,46,0.18)] hover:shadow-[0_24px_60px_-18px_rgba(255,107,107,0.28)]',
          wf.featured
            ? 'bg-gradient-to-br from-coral/[0.10] via-white/85 to-white/70 ring-coral/30'
            : 'bg-white/75 ring-white/85 hover:bg-white/85',
        )}
      >
        {wf.featured && (
          <span className="absolute -top-3 -right-2 inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[9px] font-bold uppercase tracking-[0.14em] bg-ink text-white shadow-md tabular">
            <Star size={9} className="fill-coral text-coral" />
            For You
          </span>
        )}

        <header className="flex items-start gap-3 mb-4">
          <div
            className={cn(
              'h-10 w-10 rounded-xl grid place-items-center ring-1 shrink-0',
              wf.featured
                ? 'bg-coral text-white ring-coral/40 shadow-[0_8px_20px_-8px_rgba(255,107,107,0.5)]'
                : 'bg-coral/10 text-coral ring-coral/20',
            )}
          >
            <Icon size={18} strokeWidth={2.2} />
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex items-start justify-between gap-2">
              <h3 className="text-[15px] font-bold text-ink leading-snug [text-wrap:balance]">
                {wf.title}
              </h3>
              <span
                className={cn(
                  'shrink-0 text-[9.5px] font-bold uppercase tracking-[0.1em] px-2 py-[3px] rounded-full ring-1 tabular',
                  wf.pillTone,
                )}
              >
                {wf.pillTag}
              </span>
            </div>
            <p className="mt-1.5 text-[12.5px] text-ink-muted leading-snug [text-wrap:pretty]">
              {wf.blurb}
            </p>
          </div>
        </header>

        <div className="mb-2.5 flex flex-wrap gap-1.5 justify-center">
          {wf.inputs.map((input) => (
            <InputChip key={input}>{input}</InputChip>
          ))}
        </div>

        <div>
          {wf.stages.map((stage, i) => (
            <div key={stage.label}>
              <Connector />
              <StageBox stage={stage} />
              {i === wf.stages.length - 1 && <Connector />}
            </div>
          ))}
        </div>

        <div className="mt-1 flex gap-1.5">
          {wf.tiers.map((tier) => (
            <TierPill key={tier.label} tier={tier} />
          ))}
        </div>

        <Connector />

        <div className="flex gap-1.5">
          {wf.outputs.map((output) => (
            <OutputPill key={output}>{output}</OutputPill>
          ))}
        </div>
      </article>
    </BlurFade>
  )
}

/* ─── Page ─────────────────────────────────────────────────── */
export default function ServicesPage() {
  const initiatives = siteConfig.community.initiatives
  const services = siteConfig.services

  return (
    <main className="min-h-screen pt-24">
      {/* ─── Hero ─── */}
      <section
        className="relative overflow-hidden grain"
        style={{
          background:
            'linear-gradient(180deg, #B6CCE5 0%, #FFD0C4 38%, #FFE0DA 70%, #FFEFEB 100%)',
        }}
      >
        <div className="absolute top-[14%] right-[12%] w-[340px] h-[340px] rounded-full bg-[#FFE6D2]/75 blur-[110px] pointer-events-none" />
        <div className="container-width section-padding relative">
          <div className="grid grid-cols-12 gap-6">
            <div className="col-span-12 lg:col-span-9">
              <div className="flex items-center gap-3">
                <span className="eyebrow">No. 01</span>
                <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                <span className="section-label">THE ROOMS</span>
              </div>
              <h1 className="h-display mt-7">
                <span className="block">Five rooms</span>
                <span className="block serif-italic text-coral mt-1">
                  inside the room.
                </span>
              </h1>
              <p className="text-lead mt-9 max-w-xl [text-wrap:pretty]">
                Services, but soft. Cohorts you actually finish. Each room is a
                small group of builders working on the same problem at the same
                time — with the bots, dashboards, and prompts shared.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Rooms (initiatives) ─── */}
      <section className="bg-blush relative">
        <div className="container-width section-padding">
          <div className="grid grid-cols-12 gap-6 mb-12 items-end">
            <div className="col-span-12 lg:col-span-7">
              <div className="flex items-center gap-3">
                <span className="eyebrow">No. 02</span>
                <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                <span className="section-label">WHAT WE BUILD TOGETHER</span>
              </div>
              <h2 className="h-section mt-6">
                Pick a room.{' '}
                <span className="serif-italic text-coral">Show up.</span> Ship.
              </h2>
            </div>
            <div className="col-span-12 lg:col-span-4">
              <p className="serif-italic text-ink-muted/85 text-lg leading-snug">
                Each room runs on its own cadence. Join one, or stack a few.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {initiatives.map((init, i) => {
              const Icon = iconMap[init.icon] ?? Users
              const matchService = services[i]
              return (
                <motion.div
                  key={init.title}
                  custom={i}
                  initial="hidden"
                  whileInView="visible"
                  viewport={{ once: true, margin: '-40px' }}
                  variants={fadeUp}
                >
                  <Link
                    href={`/services/${matchService?.slug ?? ''}`}
                    className={cn(
                      'group relative flex flex-col rounded-[22px] p-7 h-full overflow-hidden',
                      'bg-white/72 backdrop-blur-md ring-1 ring-rose-mist/55',
                      'hover:ring-coral/40 hover:bg-white/90 hover:-translate-y-1',
                      'transition-all duration-300 shadow-[0_10px_28px_-14px_rgba(26,26,46,0.14)]',
                    )}
                  >
                    <div className="absolute -top-16 -right-16 w-44 h-44 rounded-full bg-coral/10 blur-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                    <span className="font-mono text-[10px] tabular text-ink-faint">
                      ROOM NO.{String(i + 1).padStart(2, '0')}
                    </span>
                    <div className="mt-3 w-12 h-12 rounded-2xl bg-gradient-to-br from-coral/20 to-coral/5 ring-1 ring-coral/20 grid place-items-center">
                      <Icon size={20} className="text-coral" />
                    </div>
                    <h3 className="h-card mt-5">{init.title}</h3>
                    <p className="mt-3 text-[15px] text-ink-muted leading-[1.55] flex-1 [text-wrap:pretty]">
                      {init.clientFacing}
                    </p>
                    <div className="mt-5 flex items-center justify-between">
                      <span className="inline-flex items-center px-3 py-1.5 bg-coral-muted text-coral text-xs font-medium rounded-full tabular">
                        {init.metric}
                      </span>
                      <ArrowRight
                        size={16}
                        className="text-ink-faint group-hover:text-coral group-hover:translate-x-0.5 transition-all"
                      />
                    </div>
                  </Link>
                </motion.div>
              )
            })}
          </div>
        </div>
      </section>

      {/* ─── THE STACK — Workflow diagrams (NEW) ─── */}
      <section
        id="stack"
        className="relative overflow-hidden"
        style={{
          background:
            'linear-gradient(180deg, #FFEFEB 0%, #FFE0DA 28%, #FFD0C4 60%, #FFE4E1 100%)',
        }}
      >
        <div className="absolute top-[8%] right-[8%] w-[420px] h-[420px] rounded-full bg-[#FFE6D2]/70 blur-[120px] pointer-events-none" />
        <div className="absolute bottom-[12%] -left-32 w-[460px] h-[460px] rounded-full bg-coral/12 blur-[140px] pointer-events-none" />

        <div className="container-width section-padding relative">
          <div className="grid grid-cols-12 gap-6 lg:gap-12 mb-12">
            <div className="col-span-12 lg:col-span-7">
              <RevealOnScroll variant="blur">
                <div className="flex items-center gap-3 mb-5">
                  <span className="eyebrow">No. 03</span>
                  <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                  <span className="section-label">THE STACK</span>
                </div>
              </RevealOnScroll>

              <RevealOnScroll variant="slideUp" delay={0.05}>
                <motion.h2
                  className="font-black text-ink [text-wrap:balance]"
                  style={{
                    fontFamily: 'var(--font-satoshi)',
                    fontSize: 'clamp(1.875rem, 3.4vw, 2.875rem)',
                    lineHeight: 1.08,
                    letterSpacing: '-0.035em',
                  }}
                >
                  the actual{' '}
                  <span className="serif-italic font-normal text-coral">
                    workflows
                  </span>{' '}
                  running behind every service.
                </motion.h2>
              </RevealOnScroll>
            </div>

            <div className="col-span-12 lg:col-span-4 lg:col-start-9 lg:pt-3">
              <RevealOnScroll variant="slideUp" delay={0.1}>
                <p className="serif-italic text-ink-muted/85 text-lg leading-snug">
                  no slideware. no &ldquo;ai-powered&rdquo; vapor. these are the
                  pipelines i actually run, with the actual tools — claude,
                  clay, n8n, heygen, and the boring glue between them.
                </p>
                <div className="mt-4 flex items-center gap-2 text-xs text-ink-faint tabular">
                  <Sparkles size={12} className="text-coral" />
                  six services · ~24 stages · 30+ tools
                </div>
              </RevealOnScroll>
            </div>
          </div>

          <div className="hidden lg:flex items-center gap-2 text-[10.5px] uppercase tracking-[0.18em] text-ink-faint mb-6 tabular">
            <ChevronDown size={12} />
            scroll · each card is a live system
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-6 items-start">
            {workflows.map((wf, i) => (
              <WorkflowDiagram key={wf.slug} wf={wf} index={i} />
            ))}
          </div>

          <RevealOnScroll variant="slideUp" delay={0.1}>
            <div className="mt-16 rounded-[28px] p-8 sm:p-10 bg-ink text-white relative overflow-hidden">
              <div className="absolute -top-20 -right-20 w-[320px] h-[320px] rounded-full bg-coral/30 blur-[120px] pointer-events-none" />
              <div className="relative grid grid-cols-12 gap-6 items-center">
                <div className="col-span-12 lg:col-span-8">
                  <p className="text-[11px] uppercase tracking-[0.14em] text-coral font-bold mb-2 tabular">
                    Build with me
                  </p>
                  <h3
                    className="font-black [text-wrap:balance]"
                    style={{
                      fontFamily: 'var(--font-satoshi)',
                      fontSize: 'clamp(1.5rem, 2.6vw, 2.25rem)',
                      lineHeight: 1.1,
                      letterSpacing: '-0.03em',
                    }}
                  >
                    pick a workflow. i&rsquo;ll wire it up
                    <span className="serif-italic text-coral font-normal">
                      {' '}end-to-end{' '}
                    </span>
                    in your stack.
                  </h3>
                  <p className="mt-3 text-white/70 text-[15px] max-w-xl">
                    no decks. no waitlist. one call, one scope, one shipping
                    timeline.
                  </p>
                </div>
                <div className="col-span-12 lg:col-span-4 flex lg:justify-end">
                  <Link
                    href="/#join"
                    className="group inline-flex items-center gap-2 px-6 py-3.5 text-sm font-semibold text-ink bg-white rounded-full shadow-lg hover:bg-coral hover:text-white transition-all"
                  >
                    Book a build call
                    <ArrowRight
                      size={15}
                      className="transition-transform group-hover:translate-x-0.5"
                    />
                  </Link>
                </div>
              </div>
            </div>
          </RevealOnScroll>

          <div className="mt-8 flex items-center justify-center gap-2 text-[11px] text-ink-faint tabular">
            <ArrowUpRight size={11} />
            <span>
              tools shown are illustrative — exact stack depends on your
              existing setup.
            </span>
          </div>
        </div>
      </section>

      {/* ─── Tiers (membership tracks) ─── */}
      <section className="bg-soft-pink relative">
        <div className="container-width section-padding">
          <div className="text-center mb-14 max-w-2xl mx-auto">
            <RevealOnScroll variant="blur">
              <span className="section-label">MEMBERSHIP TRACKS</span>
            </RevealOnScroll>
            <RevealOnScroll variant="slideUp" delay={0.05}>
              <h2 className="h-section mt-6">
                Three ways to{' '}
                <span className="serif-italic text-coral">show up.</span>
              </h2>
            </RevealOnScroll>
            <RevealOnScroll variant="slideUp" delay={0.1}>
              <p className="mt-6 serif-italic text-ink-muted/85 text-lg leading-snug">
                Every track starts with the audit. Then you pick the depth.
              </p>
            </RevealOnScroll>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 max-w-5xl mx-auto">
            {siteConfig.tiers.map((tier, i) => (
              <motion.div
                key={tier.name}
                custom={i}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: '-40px' }}
                variants={fadeUp}
                className={cn(
                  'relative rounded-[22px] p-8 flex flex-col bg-white/78 backdrop-blur-md ring-1',
                  tier.popular
                    ? 'ring-2 ring-coral shadow-[0_18px_48px_-16px_rgba(255,107,107,0.3)]'
                    : 'ring-rose-mist/55 shadow-[0_10px_28px_-14px_rgba(26,26,46,0.12)]',
                )}
              >
                {tier.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 inline-flex items-center gap-1.5 px-3 py-1 bg-coral text-white text-[11px] font-bold uppercase tracking-[0.14em] rounded-full">
                    <Sparkles size={11} fill="currentColor" />
                    most picked
                  </div>
                )}
                <span className="font-mono text-[11px] tabular text-coral font-bold uppercase tracking-[0.16em]">
                  {tier.timeline}
                </span>
                <h3 className="mt-3 text-2xl font-black text-ink tracking-tight">
                  {tier.name}
                </h3>
                <p className="mt-3 text-[15px] text-ink-muted leading-[1.55] mb-6 [text-wrap:pretty]">
                  {tier.description}
                </p>
                <ul className="space-y-2.5 flex-1">
                  {tier.features.map((feature) => (
                    <li
                      key={feature}
                      className="flex items-start gap-2.5 text-sm text-ink-secondary"
                    >
                      <Check size={15} className="text-coral mt-0.5 shrink-0" />
                      <span>{feature}</span>
                    </li>
                  ))}
                </ul>
                <Link
                  href="/#join"
                  className={cn(
                    'mt-8 inline-flex items-center justify-center gap-2 px-6 py-3 rounded-full font-semibold text-sm transition-all',
                    tier.popular
                      ? 'bg-ink text-white hover:bg-ink/85'
                      : 'bg-coral-muted text-coral hover:bg-coral/15',
                  )}
                >
                  Request Invite
                  <ArrowRight size={14} />
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA ─── */}
      <section
        className="relative overflow-hidden grain"
        style={{
          background:
            'linear-gradient(180deg, #FFE4E1 0%, #FFD4C2 50%, #C9D5E8 100%)',
        }}
      >
        <div className="container-width section-padding relative text-center">
          <span className="inline-flex items-center gap-2 px-3.5 py-1.5 text-[11px] font-bold tracking-[0.16em] uppercase text-coral bg-coral/12 rounded-full ring-1 ring-coral/20">
            <Sparkles size={11} />
            THE DOOR IS OPEN TODAY
          </span>
          <h2 className="h-section mt-6 max-w-3xl mx-auto">
            Ready to <span className="serif-italic text-coral">show up?</span>
          </h2>
          <Link
            href="/#join"
            className="mt-10 inline-flex items-center gap-2.5 px-8 py-4 text-sm font-semibold text-white bg-ink rounded-full shadow-[0_10px_30px_-8px_rgba(26,26,46,0.45)] hover:-translate-y-0.5 transition-all duration-300"
          >
            Request Invite
            <ArrowRight size={15} />
          </Link>
        </div>
      </section>
    </main>
  )
}
