'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import {
  PenTool,
  Send,
  Users,
  ArrowRight,
  ArrowUpRight,
  Video,
  MessageSquare,
  Mail,
  Mic,
  Calendar,
  Wrench,
  Hammer,
  LineChart,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { cn } from '@/lib/utils'
import { RevealOnScroll } from '@/components/ui/reveal-on-scroll'
import { BlurFade } from '@/components/ui/blur-fade'
import { CountUp } from '@/components/ui/count-up'

/* ─────────────────────────────────────────────────────────────
   Tool palette — preserved from prior version.
   ───────────────────────────────────────────────────────────── */
const toolColor: Record<string, string> = {
  Claude: '#D97757',
  GPT: '#10A37F',
  Perplexity: '#21808D',
  Exa: '#7C5CFF',
  Firecrawl: '#FF6A00',
  HeyGen: '#7B61FF',
  Synthesia: '#FF4D4D',
  ElevenLabs: '#1F2937',
  Descript: '#1FA37C',
  OpusClip: '#FF5C5C',
  Reddit: '#FF4500',
  GummySearch: '#9B5BFF',
  Notion: '#111111',
  Buffer: '#168EEA',
  TweetHunter: '#1DA1F2',
  Beehiiv: '#FFC940',
  Whisper: '#74AA9C',
  Otter: '#1F87FE',
  Riverside: '#7B61FF',
  Clay: '#5BC4F1',
  n8n: '#EA4B71',
  Make: '#6D31ED',
  Apollo: '#0066FF',
  Findymail: '#22C55E',
  BuiltWith: '#1F8FFF',
  Smartlead: '#FF6B35',
  Instantly: '#3B82F6',
  CustomerIO: '#7E5BEF',
  Klaviyo: '#000000',
  HubSpot: '#FF7A59',
  LinkedIn: '#0A66C2',
  X: '#0F0F0F',
  YouTube: '#FF0000',
  Instagram: '#E1306C',
  TikTok: '#0F0F0F',
  Manual: '#6B6B80',
  Webhook: '#9B9BAD',
}

type Tool = keyof typeof toolColor

type Stage = {
  label: string
  tools: Tool[]
}

type Tier = {
  label: string
  tone: 'mint' | 'sky' | 'lilac' | 'amber' | 'coral' | 'ink'
}

type Workflow = {
  slug: string
  title: string
  blurb: string
  icon: LucideIcon
  pillTag: string
  pillTone: string
  inputs: string[]
  stages: Stage[]
  tiers: Tier[]
  outputs: string[]
  featured?: boolean
}

const tierTone: Record<Tier['tone'], string> = {
  mint: 'bg-[#2D9D78]/12 text-[#1F7256] ring-[#2D9D78]/25',
  sky: 'bg-[#5B8DEF]/14 text-[#2C5BC4] ring-[#5B8DEF]/25',
  lilac: 'bg-[#7C5CFF]/12 text-[#4F39B5] ring-[#7C5CFF]/25',
  amber: 'bg-[#F0A500]/16 text-[#A87000] ring-[#F0A500]/25',
  coral: 'bg-coral/14 text-coral ring-coral/30',
  ink: 'bg-ink/[0.08] text-ink ring-ink/20',
}

/* Preserved workflows array — same data, same shape. */
const workflows: Workflow[] = [
  {
    slug: 'content-engines',
    title: 'Content Engines',
    blurb:
      'One source recording. Twelve native assets across long-form, X, LinkedIn. You approve, the engine ships the rest.',
    icon: PenTool,
    pillTag: 'Content',
    pillTone: 'bg-[#2D9D78]/12 text-[#2D9D78] ring-[#2D9D78]/25',
    inputs: ['Brand voice', 'Topic queue', 'Source library'],
    stages: [
      { label: 'Research & evidence', tools: ['Perplexity', 'Exa', 'Firecrawl'] },
      { label: 'Outline & angle', tools: ['Claude', 'GPT'] },
      { label: 'Draft + self-edit', tools: ['Claude', 'Notion'] },
      { label: 'Adapt per platform', tools: ['Claude', 'Buffer'] },
    ],
    tiers: [
      { label: 'Long-form', tone: 'mint' },
      { label: 'Threads', tone: 'sky' },
      { label: 'Shorts', tone: 'lilac' },
    ],
    outputs: ['Blog essay', 'X thread', 'LinkedIn post'],
  },
  {
    slug: 'ugc-video',
    title: 'UGC + Short-Form Video',
    blurb:
      'A month of native reels in a weekend. Avatars, voiceovers, captions, and the boring edit pass — all autogenerated.',
    icon: Video,
    pillTag: 'Video',
    pillTone: 'bg-coral/10 text-coral ring-coral/25',
    inputs: ['Topic', 'Script outline', 'Brand assets'],
    stages: [
      { label: 'Script + hook', tools: ['Claude', 'GPT'] },
      { label: 'Avatar render', tools: ['HeyGen', 'Synthesia'] },
      { label: 'Voice clone', tools: ['ElevenLabs'] },
      { label: 'Auto-edit & captions', tools: ['Descript', 'OpusClip'] },
    ],
    tiers: [
      { label: 'Reel', tone: 'mint' },
      { label: 'Short', tone: 'sky' },
      { label: 'TikTok', tone: 'lilac' },
    ],
    outputs: ['Instagram', 'YouTube Shorts', 'X / TikTok'],
  },
  {
    slug: 'reddit-traffic',
    title: 'Reddit-Led Traffic',
    blurb:
      'Reddit shows up in 68% of AI Overviews. I build the playbook that gets your protocol cited, not just ranked.',
    icon: MessageSquare,
    pillTag: 'AI SEO',
    pillTone: 'bg-[#5B8DEF]/10 text-[#5B8DEF] ring-[#5B8DEF]/20',
    inputs: ['ICP keywords', 'Subreddit map', 'Brand POV'],
    stages: [
      { label: 'Trend mining', tools: ['Reddit', 'GummySearch'] },
      { label: 'Question matching', tools: ['Perplexity', 'Claude'] },
      { label: 'Native answer drafts', tools: ['Claude'] },
      { label: 'Cite-worthy publishing', tools: ['Manual', 'n8n'] },
    ],
    tiers: [
      { label: 'Educational', tone: 'mint' },
      { label: 'Comparison', tone: 'sky' },
      { label: 'Story', tone: 'lilac' },
    ],
    outputs: ['Google AIO cite', 'ChatGPT cite', 'Perplexity cite'],
  },
  {
    slug: 'email-lifecycle',
    title: 'Email Lifecycle, Agentic',
    blurb:
      'The flows your funnel keeps forgetting — welcome, nurture, win-back, expansion. All wired to behaviour, none of them static.',
    icon: Mail,
    pillTag: 'Lifecycle',
    pillTone: 'bg-[#F0A500]/15 text-[#A87000] ring-[#F0A500]/25',
    inputs: ['Customer events', 'Triggers', 'Brand voice'],
    stages: [
      { label: 'Behaviour listen', tools: ['n8n', 'CustomerIO'] },
      { label: 'Segment & route', tools: ['Clay', 'Make'] },
      { label: 'Personalize copy', tools: ['Claude', 'GPT'] },
      { label: 'Send + A/B test', tools: ['CustomerIO', 'Klaviyo'] },
    ],
    tiers: [
      { label: 'Welcome', tone: 'mint' },
      { label: 'Nurture', tone: 'sky' },
      { label: 'Win-back', tone: 'amber' },
    ],
    outputs: ['Onboarding flow', 'Re-engagement', 'Expansion'],
  },
  {
    slug: 'personal-brand',
    title: 'Personal Brand on Autopilot',
    blurb:
      'One 30-min recording in. A week of LinkedIn, X, and newsletter out. A ghostwriter trained on your phrasing — not a generic content mill.',
    icon: Mic,
    pillTag: 'Founder',
    pillTone: 'bg-coral text-white ring-coral/40',
    inputs: ['30-min recording', 'POV bank', 'Voice samples'],
    stages: [
      { label: 'Transcribe', tools: ['Whisper', 'Otter'] },
      { label: 'Structure & angle', tools: ['Claude'] },
      { label: 'Ghostwrite (your voice)', tools: ['Claude', 'GPT'] },
      { label: 'Schedule + ship', tools: ['Buffer', 'TweetHunter', 'Beehiiv'] },
    ],
    tiers: [
      { label: 'LinkedIn', tone: 'sky' },
      { label: 'X', tone: 'ink' },
      { label: 'Newsletter', tone: 'amber' },
    ],
    outputs: ['5 posts/wk', '3 threads/wk', '1 essay/wk'],
    featured: true,
  },
  {
    slug: 'outbound-gtm',
    title: 'Outbound + GTM Engineering',
    blurb:
      'Signal-based prospecting. AI-personalized first lines. Autonomous follow-ups. The Clay + n8n + Claude stack I run for protocols today.',
    icon: Send,
    pillTag: 'Outbound',
    pillTone: 'bg-ink/[0.08] text-ink ring-ink/15',
    inputs: ['ICP', 'Trigger signals', 'Domain list'],
    stages: [
      { label: 'Signal detection', tools: ['Clay', 'BuiltWith'] },
      { label: 'Enrich & verify', tools: ['Clay', 'Apollo', 'Findymail'] },
      { label: 'AI personalize', tools: ['Claude', 'GPT'] },
      { label: 'Send + follow-up', tools: ['Smartlead', 'Instantly', 'n8n'] },
    ],
    tiers: [
      { label: 'Tier 1', tone: 'mint' },
      { label: 'Tier 2', tone: 'sky' },
      { label: 'Tier 3', tone: 'lilac' },
    ],
    outputs: ['Calendar holds', 'Pipeline', 'Replies'],
  },
]

/* ─────────────────────────────────────────────────────────────
   Pillars (3 categories that bucket the workflows)
   ───────────────────────────────────────────────────────────── */
const pillars = [
  {
    num: '01',
    title: 'Content & Brand Systems',
    blurb:
      'Multi-agent pipelines that turn one founder voice into a month of platform-native posts, video, and citations. Built around the brand, not against it.',
    tools: ['Claude', 'HeyGen', 'ElevenLabs', 'Buffer'] as Tool[],
    href: '#content-engines',
    Icon: PenTool,
  },
  {
    num: '02',
    title: 'Outbound & Pipeline',
    blurb:
      'Signal-based prospecting layered with on-chain enrichment. The same Clay-driven sequences I shipped on stage in Mumbai and now run for Canton-adjacent protocols.',
    tools: ['Clay', 'Apollo', 'Smartlead', 'n8n'] as Tool[],
    href: '#outbound-gtm',
    Icon: Send,
  },
  {
    num: '03',
    title: 'Community & Events',
    blurb:
      'The DeKoded methodology — IRL rooms that ship — paired with Discord and Telegram bots that absorb 80% of the repeat questions when you scale.',
    tools: ['n8n', 'Notion', 'Webhook', 'Claude'] as Tool[],
    href: '#email-lifecycle',
    Icon: Users,
  },
]

/* ─────────────────────────────────────────────────────────────
   Worked-with strip
   ───────────────────────────────────────────────────────────── */
const workedWith = [
  { name: 'Canton Foundation', context: 'Marketing the rails moving $9T/month' },
  { name: 'KRNL Labs', context: 'DeKoded ecosystem lead, 6-city tour' },
  { name: 'Smallest AI', context: 'Voice agents shipping in production today' },
  { name: 'Symbiote', context: 'Inside Web3 marketing, 2024' },
  { name: 'Genzio Media', context: 'Where the agency-vs-builder gap got loud' },
]

/* ─────────────────────────────────────────────────────────────
   Process rows
   ───────────────────────────────────────────────────────────── */
const processRows = [
  {
    n: '01',
    step: 'Strategy Call',
    what: 'A 45-minute working session. We map your funnel, your stack, and the one bottleneck that — if cleared — moves the next quarter.',
    you: 'Show up with current numbers. No deck required.',
    when: 'Day 0',
    Icon: Calendar,
  },
  {
    n: '02',
    step: 'Workshop',
    what: 'I rebuild the chosen workflow on a shared screen. You watch the prompts, the Clay tables, the n8n graph. Nothing is a black box.',
    you: 'Two hours, your stack credentials, a sandbox env.',
    when: 'Week 1',
    Icon: Wrench,
  },
  {
    n: '03',
    step: 'Build & Deploy',
    what: 'The system goes live in your production stack — your Slack, your inbox, your CRM. You own every credential, every template.',
    you: 'Async reviews. One mid-build sync.',
    when: 'Weeks 2 to 5',
    Icon: Hammer,
  },
  {
    n: '04',
    step: 'Optimize',
    what: 'Weekly numbers. We tune what is firing, kill what is not, and scope the next workflow on top of the one that just shipped.',
    you: 'A 30-min review cadence — that is it.',
    when: 'Weeks 6+',
    Icon: LineChart,
  },
]

/* ─────────────────────────────────────────────────────────────
   Results case strip
   ───────────────────────────────────────────────────────────── */
const cases = [
  {
    headline: '$340K',
    unit: 'pipeline shipped',
    context: 'Goa 3-day retreat — one launch, end-to-end, in 72 hours.',
  },
  {
    headline: '130K',
    unit: 'tour views',
    context: 'H1 2025 India tour content — across X, LinkedIn, and YouTube.',
  },
  {
    headline: '140+',
    unit: 'founders convened',
    context: 'Dubai DeKoded — first international room, GCC outbound playbook.',
  },
  {
    headline: '$9T/mo',
    unit: 'institutional flow',
    context: 'Canton Foundation marketing — proving editorial works for infra.',
  },
]

/* ─────────────────────────────────────────────────────────────
   Comparison rows — Muskan vs Agency vs SaaS vs Junior
   ───────────────────────────────────────────────────────────── */
const compareRows = [
  {
    criterion: 'Has actually shipped Web3 GTM',
    muskan: 'Canton, KRNL, Symbiote — three deployments live',
    agency: 'Two case studies from 2022, mostly CEX',
    saas: 'Templates, no domain context',
    junior: 'Read a Bankless article last week',
  },
  {
    criterion: 'AI workflows running in production',
    muskan: 'Six pipelines live across three protocols',
    agency: 'A ChatGPT subscription on the company card',
    saas: 'You build the workflow yourself',
    junior: 'Knows the prompts, not the wiring',
  },
  {
    criterion: 'Time to first ship',
    muskan: 'Workshop in week one. Live in five.',
    agency: 'Six-week onboarding, then a deck',
    saas: 'Whenever you finish reading the docs',
    junior: 'Three months ramp, optimistic',
  },
  {
    criterion: 'Embedded in your stack',
    muskan: 'Yes — your Slack, your CRM, your sandbox',
    agency: 'A weekly status call and a Notion page',
    saas: 'A dashboard you open on Mondays',
    junior: 'Yes, but they also need managing',
  },
  {
    criterion: 'One person accountable end-to-end',
    muskan: 'Me. The same person who scoped it.',
    agency: 'An account manager and three handoffs',
    saas: 'A support inbox',
    junior: 'You, ultimately',
  },
]

/* ─────────────────────────────────────────────────────────────
   Reusable atoms (preserved from prior file)
   ───────────────────────────────────────────────────────────── */
function ToolChip({ name }: { name: Tool }) {
  const color = toolColor[name] ?? '#6B6B80'
  return (
    <span className="inline-flex items-center gap-1.5 px-2 py-[3px] rounded-md bg-white/85 ring-1 ring-ink/10 text-[10.5px] font-medium text-ink/85 tabular shadow-[0_1px_2px_rgba(26,26,46,0.04)]">
      <span
        className="h-1.5 w-1.5 rounded-full shrink-0"
        style={{ backgroundColor: color }}
        aria-hidden
      />
      {name}
    </span>
  )
}

function InputChip({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center px-2.5 py-1 rounded-full bg-white/70 ring-1 ring-ink/10 text-[10.5px] font-medium text-ink-muted tabular">
      {children}
    </span>
  )
}

function TierPill({ tier }: { tier: Tier }) {
  return (
    <span
      className={cn(
        'inline-flex text-center text-[10.5px] font-bold uppercase tracking-[0.1em] px-2.5 py-1.5 rounded-full ring-1 tabular',
        tierTone[tier.tone],
      )}
    >
      {tier.label}
    </span>
  )
}

function OutputPill({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex text-center text-[11px] font-bold uppercase tracking-[0.08em] px-3 py-1.5 rounded-lg bg-ink text-white shadow-[0_6px_18px_-8px_rgba(26,26,46,0.6)] tabular">
      {children}
    </span>
  )
}

/* ─────────────────────────────────────────────────────────────
   Workflow card — wide, horizontal layout (one per row).
   Inputs on the left, stages middle, tiers + outputs right.
   ───────────────────────────────────────────────────────────── */
function WorkflowRow({ wf, index }: { wf: Workflow; index: number }) {
  const Icon = wf.icon
  return (
    <BlurFade delay={0.05 + index * 0.04} yOffset={18} blur={6}>
      <article
        id={wf.slug}
        className={cn(
          'relative rounded-[24px] p-6 sm:p-8 backdrop-blur-md ring-1 transition-all scroll-mt-28',
          'shadow-[0_18px_50px_-22px_rgba(26,26,46,0.18)]',
          wf.featured
            ? 'bg-gradient-to-br from-coral/[0.10] via-white/85 to-white/72 ring-coral/30'
            : 'bg-white/78 ring-white/85 hover:bg-white/88',
        )}
      >
        <div className="grid grid-cols-12 gap-6 lg:gap-8">
          {/* Header column */}
          <header className="col-span-12 lg:col-span-4 flex flex-col">
            <div className="flex items-start gap-3">
              <div
                className={cn(
                  'h-11 w-11 rounded-xl grid place-items-center ring-1 shrink-0',
                  wf.featured
                    ? 'bg-coral text-white ring-coral/40 shadow-[0_8px_20px_-8px_rgba(255,107,107,0.5)]'
                    : 'bg-coral/10 text-coral ring-coral/20',
                )}
              >
                <Icon size={20} strokeWidth={2.2} />
              </div>
              <div className="min-w-0 flex-1">
                <span
                  className={cn(
                    'inline-flex shrink-0 text-[9.5px] font-bold uppercase tracking-[0.1em] px-2 py-[3px] rounded-full ring-1 tabular mb-1.5',
                    wf.pillTone,
                  )}
                >
                  {wf.pillTag}
                </span>
                <h3 className="h-card text-[20px] sm:text-[22px] leading-snug [text-wrap:balance]">
                  {wf.title}
                </h3>
              </div>
            </div>

            <p className="mt-4 text-[14.5px] text-ink-muted leading-[1.6] [text-wrap:pretty]">
              {wf.blurb}
            </p>

            <div className="mt-5">
              <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint mb-2">
                Inputs
              </p>
              <div className="flex flex-wrap gap-1.5">
                {wf.inputs.map((input) => (
                  <InputChip key={input}>{input}</InputChip>
                ))}
              </div>
            </div>
          </header>

          {/* Stages column */}
          <div className="col-span-12 lg:col-span-5">
            <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint mb-3">
              Stages
            </p>
            <ol className="space-y-2">
              {wf.stages.map((stage, i) => (
                <li
                  key={stage.label}
                  className="flex items-start gap-3 rounded-xl bg-white/65 ring-1 ring-ink/8 px-3 py-2.5"
                >
                  <span className="font-mono text-[10px] tabular text-coral font-bold mt-0.5 shrink-0 w-5">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <div className="min-w-0 flex-1">
                    <p className="text-[12.5px] font-semibold text-ink leading-tight">
                      {stage.label}
                    </p>
                    <div className="mt-1.5 flex flex-wrap gap-1">
                      {stage.tools.map((tool) => (
                        <ToolChip key={tool} name={tool} />
                      ))}
                    </div>
                  </div>
                </li>
              ))}
            </ol>
          </div>

          {/* Outputs column */}
          <div className="col-span-12 lg:col-span-3 flex flex-col gap-5">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint mb-2">
                Tiers
              </p>
              <div className="flex flex-wrap gap-1.5">
                {wf.tiers.map((tier) => (
                  <TierPill key={tier.label} tier={tier} />
                ))}
              </div>
            </div>
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint mb-2">
                Ships
              </p>
              <div className="flex flex-wrap gap-1.5">
                {wf.outputs.map((output) => (
                  <OutputPill key={output}>{output}</OutputPill>
                ))}
              </div>
            </div>
          </div>
        </div>
      </article>
    </BlurFade>
  )
}

/* ─────────────────────────────────────────────────────────────
   Page
   ───────────────────────────────────────────────────────────── */
export default function ServicesPage() {
  return (
    <main className="min-h-screen pt-24">

      {/* ─── 1. Hero ─── */}
      <section className="bg-blush relative">
        <div className="container-width section-padding">
          <div className="grid grid-cols-12 gap-8 lg:gap-12 items-end">

            {/* Left — copy */}
            <div className="col-span-12 lg:col-span-8">
              <BlurFade delay={0} duration={0.5}>
                <div className="flex items-center gap-3">
                  <span className="eyebrow">No. 01</span>
                  <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                  <span className="section-label">SERVICES</span>
                </div>
              </BlurFade>

              <RevealOnScroll variant="slideUp" stagger={0.1} delay={0.08} className="mt-7">
                <h1 className="h-display">
                  <span className="block">AI Systems for</span>
                </h1>
                <h1 className="h-display">
                  <span className="block">Web3 GTM Teams</span>
                </h1>
                <h1 className="h-display">
                  <span className="block serif-italic text-coral mt-1">
                    Tired of Slideware.
                  </span>
                </h1>
              </RevealOnScroll>

              <BlurFade delay={0.42} duration={0.55} yOffset={12}>
                <p className="text-lead mt-9 max-w-2xl [text-wrap:pretty]">
                  I run marketing for Canton Foundation — the blockchain settling
                  $9T per month in institutional flow. Before that, I shipped the
                  DeKoded tour across six Indian cities and convened 600+ builders
                  on the way. The systems on this page are the same ones I deploy
                  inside protocol teams. No decks, no outsourced juniors, no
                  &ldquo;AI-powered&rdquo; vapor.
                </p>
              </BlurFade>

              <BlurFade delay={0.58} duration={0.5} yOffset={10}>
                <div className="mt-9 flex flex-wrap items-center gap-3">
                  <Link
                    href="/book"
                    className="group inline-flex items-center gap-2.5 px-7 py-3.5 text-sm font-semibold text-white bg-ink rounded-full shadow-[0_10px_30px_-8px_rgba(26,26,46,0.45)] hover:-translate-y-0.5 transition-all duration-300"
                  >
                    Book a Strategy Call
                    <ArrowRight size={15} className="transition-transform group-hover:translate-x-0.5" />
                  </Link>
                  <a
                    href="#workflows"
                    className="inline-flex items-center gap-2 px-7 py-3.5 text-sm font-semibold text-ink/85 bg-white/60 backdrop-blur-md rounded-full ring-1 ring-ink/10 hover:bg-white/85 transition-all duration-300"
                  >
                    See the Stack
                    <ArrowRight size={14} className="rotate-90" />
                  </a>
                </div>
              </BlurFade>
            </div>

            {/* Right — stat triplet */}
            <div className="col-span-12 lg:col-span-4">
              <BlurFade delay={0.3} duration={0.55} yOffset={16}>
                <div className="grid grid-cols-1 gap-3">
                  <div className="rounded-[18px] p-5 bg-white/72 backdrop-blur-md ring-1 ring-rose-mist/55">
                    <p className="font-mono text-[10px] tabular text-coral font-bold uppercase tracking-[0.18em]">
                      Canton scale
                    </p>
                    <p className="mt-2 font-black text-3xl text-ink tabular tracking-tight leading-none">
                      $9T<span className="text-coral">/mo</span>
                    </p>
                    <p className="mt-1.5 text-[12px] text-ink-muted leading-snug">
                      Institutional blockchain flow we market today.
                    </p>
                  </div>
                  <div className="rounded-[18px] p-5 bg-white/72 backdrop-blur-md ring-1 ring-rose-mist/55">
                    <p className="font-mono text-[10px] tabular text-coral font-bold uppercase tracking-[0.18em]">
                      Builders convened
                    </p>
                    <p className="mt-2 font-black text-3xl text-ink tabular tracking-tight leading-none">
                      <CountUp value={600} suffix="+" />
                    </p>
                    <p className="mt-1.5 text-[12px] text-ink-muted leading-snug">
                      Across DeKoded and Build Club rooms since 2024.
                    </p>
                  </div>
                  <div className="rounded-[18px] p-5 bg-ink text-white ring-1 ring-white/10">
                    <p className="font-mono text-[10px] tabular text-coral font-bold uppercase tracking-[0.18em]">
                      Cities operated
                    </p>
                    <p className="mt-2 font-black text-3xl text-white tabular tracking-tight leading-none">
                      8<span className="text-coral"> rooms</span>
                    </p>
                    <p className="mt-1.5 text-[12px] text-white/60 leading-snug">
                      BLR · DEL · BOM · HYD · PNQ · GOI · DXB live · SIN Q3 26
                    </p>
                  </div>
                </div>
              </BlurFade>
            </div>
          </div>
        </div>
      </section>

      {/* ─── 2. Worked With strip ─── */}
      <section className="bg-ink text-white relative overflow-hidden">
        <div className="container-width py-12 lg:py-14 px-6 sm:px-8">
          <div className="flex items-center gap-3 mb-8">
            <span className="h-px w-10 bg-white/15" />
            <span className="inline-flex items-center gap-2 px-3 py-1 text-[10.5px] font-bold tracking-[0.18em] uppercase text-coral bg-coral/10 rounded-full ring-1 ring-coral/20">
              Shipped Inside
            </span>
            <span className="h-px flex-1 bg-white/10" />
          </div>

          <RevealOnScroll variant="slideUp" stagger={0.08} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-px bg-white/[0.04] rounded-2xl overflow-hidden">
            {workedWith.map((w) => (
              <div
                key={w.name}
                className="bg-midnight-card hover:bg-midnight-elevated transition-colors duration-300 px-5 py-6"
              >
                <p className="font-black text-white text-[18px] tracking-tight leading-tight">
                  {w.name}
                </p>
                <p className="mt-2 text-[12px] text-white/55 leading-snug">
                  {w.context}
                </p>
              </div>
            ))}
          </RevealOnScroll>
        </div>
      </section>

      {/* ─── 3. The 3 Pillars ─── */}
      <section className="bg-blush relative">
        <div className="container-width section-padding">
          <div className="grid grid-cols-12 gap-6 mb-12 items-end">
            <BlurFade delay={0} className="col-span-12 lg:col-span-7">
              <div className="flex items-center gap-3">
                <span className="eyebrow">No. 02</span>
                <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                <span className="section-label">THE THREE PILLARS</span>
              </div>
              <h2 className="h-section mt-6">
                Three places where AI{' '}
                <span className="serif-italic text-coral">earns its keep.</span>
              </h2>
            </BlurFade>
            <BlurFade delay={0.15} className="col-span-12 lg:col-span-4">
              <p className="serif-italic text-ink-muted/85 text-lg leading-snug">
                Pick the pillar that hurts most. We start there.
              </p>
            </BlurFade>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
            {pillars.map((p, i) => {
              const Icon = p.Icon
              return (
                <motion.div
                  key={p.num}
                  initial={{ opacity: 0, y: 22, filter: 'blur(4px)' }}
                  whileInView={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
                  viewport={{ once: true, margin: '-40px' }}
                  transition={{
                    duration: 0.55,
                    delay: i * 0.08,
                    ease: [0.22, 1, 0.36, 1],
                  }}
                  className="group relative flex flex-col rounded-[22px] p-7 h-full bg-white/75 backdrop-blur-md ring-1 ring-rose-mist/55 hover:ring-coral/40 hover:bg-white/90 hover:-translate-y-1 transition-all duration-300 shadow-[0_10px_28px_-14px_rgba(26,26,46,0.14)]"
                >
                  <div className="flex items-start justify-between">
                    <span className="font-mono text-[11px] tabular text-coral font-bold tracking-[0.18em]">
                      PILLAR {p.num}
                    </span>
                    <Icon size={18} className="text-coral/70" />
                  </div>
                  <h3 className="h-card mt-5 [text-wrap:balance]">{p.title}</h3>
                  <p className="mt-3 text-[14.5px] text-ink-muted leading-[1.6] flex-1 [text-wrap:pretty]">
                    {p.blurb}
                  </p>
                  <div className="mt-5 flex flex-wrap gap-1.5">
                    {p.tools.map((tool) => (
                      <ToolChip key={tool} name={tool} />
                    ))}
                  </div>
                  <a
                    href={p.href}
                    className="mt-6 inline-flex items-center gap-1.5 text-[13px] font-semibold text-ink hover:text-coral transition-colors"
                  >
                    Explore the workflows
                    <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
                  </a>
                </motion.div>
              )
            })}
          </div>
        </div>
      </section>

      {/* ─── 4. The Workflows ─── */}
      <section id="workflows" className="bg-soft-pink relative">
        <div className="container-width section-padding">
          <div className="grid grid-cols-12 gap-6 mb-12 items-end">
            <BlurFade delay={0} className="col-span-12 lg:col-span-7">
              <div className="flex items-center gap-3">
                <span className="eyebrow">No. 03</span>
                <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                <span className="section-label">THE STACK</span>
              </div>
              <h2 className="h-section mt-6">
                Six Workflows.{' '}
                <span className="serif-italic text-coral">All in production.</span>
              </h2>
            </BlurFade>
            <BlurFade delay={0.15} className="col-span-12 lg:col-span-4">
              <p className="serif-italic text-ink-muted/85 text-lg leading-snug">
                Inputs in. Stages mapped to actual tools. Outputs you can hold.
              </p>
              <div className="mt-3 flex items-center gap-2 text-[11px] text-ink-faint tabular">
                six systems · ~24 stages · 30+ tools
              </div>
            </BlurFade>
          </div>

          <div className="flex flex-col gap-5">
            {workflows.map((wf, i) => (
              <WorkflowRow key={wf.slug} wf={wf} index={i} />
            ))}
          </div>

          <div className="mt-8 flex items-center justify-center gap-2 text-[11.5px] text-ink-faint tabular">
            <ArrowUpRight size={11} />
            <span>
              Tools shown are illustrative. Final stack is fitted to whatever you already pay for.
            </span>
          </div>
        </div>
      </section>

      {/* ─── 5. Process ─── */}
      <section className="bg-blush relative">
        <div className="container-width section-padding">
          <div className="grid grid-cols-12 gap-6 mb-10 items-end">
            <BlurFade delay={0} className="col-span-12 lg:col-span-7">
              <div className="flex items-center gap-3">
                <span className="eyebrow">No. 04</span>
                <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                <span className="section-label">HOW WE WORK</span>
              </div>
              <h2 className="h-section mt-6">
                Four Steps.{' '}
                <span className="serif-italic text-coral">No mystery.</span>
              </h2>
            </BlurFade>
            <BlurFade delay={0.15} className="col-span-12 lg:col-span-4">
              <p className="serif-italic text-ink-muted/85 text-lg leading-snug">
                Same process I run for protocol teams today.
              </p>
            </BlurFade>
          </div>

          <RevealOnScroll variant="slideUp" delay={0.05}>
            <div className="rounded-[22px] bg-white/72 backdrop-blur-md ring-1 ring-rose-mist/55 overflow-hidden shadow-[0_10px_28px_-14px_rgba(26,26,46,0.12)]">
              <div className="hidden md:grid grid-cols-12 gap-4 px-6 py-4 bg-ink/[0.04] border-b border-ink/8">
                <span className="col-span-1 text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint tabular">#</span>
                <span className="col-span-3 text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint">Step</span>
                <span className="col-span-5 text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint">What happens</span>
                <span className="col-span-2 text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint">Your part</span>
                <span className="col-span-1 text-[10px] font-bold uppercase tracking-[0.16em] text-ink-faint text-right">Timeline</span>
              </div>

              <ol>
                {processRows.map((row) => {
                  const Icon = row.Icon
                  return (
                    <li
                      key={row.n}
                      className="grid grid-cols-12 gap-4 px-6 py-6 border-b border-ink/8 last:border-b-0 hover:bg-white/40 transition-colors"
                    >
                      <span className="col-span-2 md:col-span-1 font-mono text-[14px] tabular text-coral font-bold">
                        {row.n}
                      </span>
                      <div className="col-span-10 md:col-span-3 flex items-center gap-2.5">
                        <Icon size={16} className="text-coral/70 shrink-0" />
                        <span className="text-[15px] font-bold text-ink leading-tight">
                          {row.step}
                        </span>
                      </div>
                      <p className="col-span-12 md:col-span-5 text-[14px] text-ink-secondary leading-[1.55] [text-wrap:pretty]">
                        {row.what}
                      </p>
                      <p className="col-span-8 md:col-span-2 text-[13px] text-ink-muted leading-[1.5]">
                        {row.you}
                      </p>
                      <span className="col-span-4 md:col-span-1 text-[12px] font-bold uppercase tracking-[0.1em] text-ink-faint tabular md:text-right">
                        {row.when}
                      </span>
                    </li>
                  )
                })}
              </ol>
            </div>
          </RevealOnScroll>
        </div>
      </section>

      {/* ─── 6. Results / Case Strip ─── */}
      <section className="bg-soft-pink relative">
        <div className="container-width section-padding">
          <div className="grid grid-cols-12 gap-6 mb-10 items-end">
            <BlurFade delay={0} className="col-span-12 lg:col-span-7">
              <div className="flex items-center gap-3">
                <span className="eyebrow">No. 05</span>
                <span className="h-px flex-1 max-w-[80px] bg-ink/15" />
                <span className="section-label">RECEIPTS</span>
              </div>
              <h2 className="h-section mt-6">
                Numbers from{' '}
                <span className="serif-italic text-coral">rooms I have already run.</span>
              </h2>
            </BlurFade>
            <BlurFade delay={0.15} className="col-span-12 lg:col-span-4">
              <p className="serif-italic text-ink-muted/85 text-lg leading-snug">
                Not projections. Not case studies. Things that happened.
              </p>
            </BlurFade>
          </div>

          <RevealOnScroll variant="slideUp" stagger={0.08} className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {cases.map((c) => (
              <div
                key={c.headline}
                className="rounded-[20px] p-6 bg-white/75 backdrop-blur-md ring-1 ring-rose-mist/55 shadow-[0_10px_28px_-14px_rgba(26,26,46,0.12)] hover:-translate-y-1 hover:ring-coral/35 transition-all duration-300"
              >
                <p className="font-black text-3xl sm:text-4xl text-ink tabular tracking-tight leading-none">
                  {c.headline}
                </p>
                <p className="mt-2 text-[11px] font-bold uppercase tracking-[0.14em] text-coral">
                  {c.unit}
                </p>
                <p className="mt-3 text-[13px] text-ink-muted leading-[1.55] [text-wrap:pretty]">
                  {c.context}
                </p>
              </div>
            ))}
          </RevealOnScroll>
        </div>
      </section>

      {/* ─── 7. Why Me, Not Them ─── */}
      <section className="bg-ink text-white relative">
        <div className="container-width section-padding">
          <div className="grid grid-cols-12 gap-6 mb-10 items-end">
            <BlurFade delay={0} className="col-span-12 lg:col-span-7">
              <div className="flex items-center gap-3">
                <span className="h-px w-10 bg-white/15" />
                <span className="inline-flex items-center gap-2 px-3 py-1 text-[10.5px] font-bold tracking-[0.18em] uppercase text-coral bg-coral/10 rounded-full ring-1 ring-coral/20">
                  No. 06 · The Honest Comparison
                </span>
              </div>
              <h2 className="h-section mt-6 text-white">
                Pick the column that fits{' '}
                <span className="serif-italic text-coral">your next quarter.</span>
              </h2>
            </BlurFade>
            <BlurFade delay={0.15} className="col-span-12 lg:col-span-4">
              <p className="serif-italic text-white/55 text-lg leading-snug">
                I am not the right answer for everyone. I am the right answer for some.
              </p>
            </BlurFade>
          </div>

          <RevealOnScroll variant="slideUp" delay={0.05}>
            <div className="rounded-[22px] bg-white/[0.04] ring-1 ring-white/10 overflow-hidden">
              {/* Header row */}
              <div className="hidden md:grid grid-cols-12 gap-4 px-6 py-4 bg-white/[0.04] border-b border-white/8">
                <span className="col-span-3 text-[10px] font-bold uppercase tracking-[0.16em] text-white/45">
                  Criterion
                </span>
                <span className="col-span-3 text-[10px] font-bold uppercase tracking-[0.16em] text-coral">
                  Muskan
                </span>
                <span className="col-span-2 text-[10px] font-bold uppercase tracking-[0.16em] text-white/45">
                  Agency
                </span>
                <span className="col-span-2 text-[10px] font-bold uppercase tracking-[0.16em] text-white/45">
                  SaaS Tool
                </span>
                <span className="col-span-2 text-[10px] font-bold uppercase tracking-[0.16em] text-white/45">
                  Junior Hire
                </span>
              </div>

              <ul>
                {compareRows.map((row, i) => (
                  <li
                    key={row.criterion}
                    className={cn(
                      'grid grid-cols-12 gap-4 px-6 py-5 border-b border-white/8 last:border-b-0',
                      i % 2 === 1 && 'bg-white/[0.015]',
                    )}
                  >
                    <p className="col-span-12 md:col-span-3 text-[13.5px] font-bold text-white leading-[1.4] [text-wrap:balance]">
                      {row.criterion}
                    </p>
                    <p className="col-span-12 md:col-span-3 text-[13px] text-coral/95 leading-[1.55] [text-wrap:pretty]">
                      <span className="md:hidden inline-block text-[10px] uppercase tracking-[0.14em] text-coral/70 font-bold mr-2">Muskan ·</span>
                      {row.muskan}
                    </p>
                    <p className="col-span-12 md:col-span-2 text-[12.5px] text-white/55 leading-[1.55] [text-wrap:pretty]">
                      <span className="md:hidden inline-block text-[10px] uppercase tracking-[0.14em] text-white/35 font-bold mr-2">Agency ·</span>
                      {row.agency}
                    </p>
                    <p className="col-span-12 md:col-span-2 text-[12.5px] text-white/55 leading-[1.55] [text-wrap:pretty]">
                      <span className="md:hidden inline-block text-[10px] uppercase tracking-[0.14em] text-white/35 font-bold mr-2">SaaS ·</span>
                      {row.saas}
                    </p>
                    <p className="col-span-12 md:col-span-2 text-[12.5px] text-white/55 leading-[1.55] [text-wrap:pretty]">
                      <span className="md:hidden inline-block text-[10px] uppercase tracking-[0.14em] text-white/35 font-bold mr-2">Junior ·</span>
                      {row.junior}
                    </p>
                  </li>
                ))}
              </ul>
            </div>
          </RevealOnScroll>
        </div>
      </section>

      {/* ─── 8. CTA ─── */}
      <section className="bg-blush relative">
        <div className="container-width section-padding">
          <div className="rounded-[28px] p-10 sm:p-14 bg-ink text-white relative overflow-hidden ring-1 ring-white/8">
            <div className="absolute -top-24 -right-24 w-[360px] h-[360px] rounded-full bg-coral/25 blur-[140px] pointer-events-none" />
            <div className="relative grid grid-cols-12 gap-8 items-center">
              <div className="col-span-12 lg:col-span-8">
                <span className="inline-flex items-center gap-2 px-3 py-1 text-[10.5px] font-bold tracking-[0.18em] uppercase text-coral bg-coral/10 rounded-full ring-1 ring-coral/20">
                  Step One
                </span>
                <h2 className="h-section mt-5 text-white [text-wrap:balance]">
                  Which workflow would{' '}
                  <span className="serif-italic text-coral">actually move your number?</span>
                </h2>
                <p className="mt-5 text-white/65 text-[16px] max-w-xl leading-[1.6]">
                  45 minutes on a call. We map the bottleneck, scope the first
                  build, and you decide if the next step is worth taking. No deck
                  on the way out.
                </p>
              </div>
              <div className="col-span-12 lg:col-span-4 flex lg:justify-end">
                <Link
                  href="/book"
                  className="group inline-flex items-center gap-2.5 px-8 py-4 text-sm font-semibold text-ink bg-white rounded-full shadow-[0_12px_32px_-10px_rgba(255,255,255,0.5)] hover:bg-coral hover:text-white transition-all"
                >
                  Book a Strategy Call
                  <ArrowRight size={15} className="transition-transform group-hover:translate-x-0.5" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

    </main>
  )
}
